### ISSUE TITLE
Select and Prep Header Image for About Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/north-texas-evictions#119]
## Objective
We will be purchasing [this getty image](https://www.gettyimages.com/detail/news-photo/the-belongings-of-shanta-thomas-remain-outside-of-the-news-photo/1231502932?adppopup=true) to feature on the About page. This story is intended to prepare the image to be featured. 

## Order of Operations
- [x] [ @sashasashasasha ] Update About page mockups to feature aforementioned getty image
- [x] [ @sashasashasasha  ] Define the max resolution needed to feature image (please factor in retina screens @2x)
- [x] [ @james-minton  ] Purchase proper size image based on Sasha's recommendations
- [x] [ @sashasashasasha ] Complete any needed photo editing/treatment to prep image for live site
- [ ] [ @alegzandach  ] Update About page with new Getty image

**Comment by sashasashasasha** [comment]
I have updated the mockups [here](https://www.figma.com/file/dkl0IqDVYtMFLVxIlG4vQM/Dashboard?node-id=521%3A1040)

The image would need to be at least 1000px wide

**Comment by ekmason** [comment]
Thanks @sashasashasasha ! Handing this off to @alegzandach for implementation.
