### ISSUE TITLE
Map Component

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/north-texas-evictions#15]
dependency on #4 

- [x] shows choropleth layer for the active choropleth metric (if any) for the selected region
  - [x] show an outline with no fill if no metric selected
- [x] shows bubbles that correspond to the active eviction metric for the selected region
- [x] choropleths + bubbles have a hover state when hovered
- [x] chorpleths + bubbles have a selected state when selected
- [x] tooltip shows readout of data metrics on hover
- [x] places with demographic data unavailable show a unavailable choropleth state
- [x] places with eviction data unavailable show an unavailable bubble state

**Comment by sashasashasasha** [comment]
@Lane when a choropleth and bubble are selected what happens next?

**Comment by Lane** [comment]
@sashasashasasha not much on this iteration.  in future phases we will show a data summary for the location.
