### ISSUE TITLE
Create modal detailing short term data issues

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/north-texas-evictions#165]
Create a dismissible modal which appears on load of [the website](https://northtexasevictions.org/#/map/counties/efr/mhi/2021-01-01/2022-10-28/8.961/32.989/-96.923?group=avg7), reading

> Note: Dallas County is transitioning to a new data system. As a result, the most recent upload of new eviction filing data for Dallas County was October 25, 2022. Collin, Denton, and Tarrant Counties continue to be updated weekly.

**Comment by cfhull** [comment]
Looking for anything fancier than this? I store the state in local storage so returning users don't see it every time. Seemed reasonable. Functionality can be reviewed/tested at the linked PR.

![image](https://user-images.githubusercontent.com/5115526/203190411-e85f291a-03f0-4eea-a66c-73bc50fdc807.png)

**Comment by james-minton** [comment]
Looks good! Can you just cut the black border around the modal and then merge it live?
