### ISSUE TITLE
Detailed Location View

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/north-texas-evictions#73]
## Objective
Design and implement a location panel to include the following: 
- list of all eviction metrics (# of filings, rate, total amount, median amount)
- time series for all eviction metrics (ref: [time series part 1 ticket](https://app.zenhub.com/workspaces/nt-evictions-6104348a917ef90013df21bf/issues/hyperobjekt/north-texas-evictions/39)) 
- list of all available demographic metrics
- ability to filter within region (ref: [region filtering ticket](https://app.zenhub.com/workspaces/nt-evictions-6104348a917ef90013df21bf/issues/hyperobjekt/north-texas-evictions/60)) 

## Background
Request from initial scope document:
>The website should display change in eviction filings over time for a selected geography. E.g., a user might want to know how many evictions were filed in the City of Dallas in 2020 compared to 2019 or how the eviction filing rate has trended in a particular zip code since 2017.

**Comment by Lane** [comment]
## Spec

- locations can be "selected" by clicking on the map or search
- when a location is selected:
  - a panel opens with additional information for the corresponding location
  - the corresponding location is highlighted on the map
- the panel contains the following information:
  - location name
  - indication of time range
  - total eviction filings, with a trend line for the selected time range 
  - total amount filed in the selected time range
  - median filing amount for the selected time range
  - demographic data (median household income, poverty rate, etc.)
- the panel should have a button that allows the user to toggle on/off "pinned" status (see #60)
- the panel should have a button that allows the user to switch to the corresponding region for the location, if the map is currently on a different region
- the app route should have a query parameter that indicates the selected location (for direct linking)
- when the app loads, the active location should be loaded from the route (if any)
